# Generated by Django 4.2.4 on 2023-08-14 10:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('artist', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('origin_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='origin_image')),
                ('stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('paintings', 'Paintings'), ('sculptures', 'Sculptures'), ('frames', 'Frames'), ('crafts', 'Crafts')], max_length=20)),
            ],
        ),
    ]
