# Generated by Django 4.2.4 on 2023-10-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_origin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='SALE', max_length=10),
            preserve_default=False,
        ),
    ]
