# Generated by Django 4.2.4 on 2023-11-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
